name: CI
on: 
  pull_request:
    branches:    
    - main

jobs:
  RunTests:
    runs-on: windows-latest
    steps:
      - name: Checkout psplaceholders
        uses: actions/checkout@v3.5.2
      - name: Checkout pstools
        uses: actions/checkout@v3.5.2
        with:
          repository: gogbg/pstools
          path: pstools
      - name: Initialize ps env
        shell: pwsh
        run: |
          ./pstools/Initialize-Env.ps1
      - name: Install module dependencies
        shell: pwsh
        run: |
          ./pstools/Install-ModuleDep.ps1 -ModulePath './src/psplaceholders'
      - name: Run pester tests
        shell: pwsh
        run: |
          ./pstools/Invoke-Pester.ps1 -TestPath './.tests/'
        
          
